// Makes src/ui/assets/atlas-image.js from the player's illustrated map (M3 spec §5.6, A9).
//
// It pulls the embedded PNG out of /home/user/New-game/aethermoor-interactive-image-map-polished.html
// (window.__AETHERMOOR_EMBEDDED_MAP_ART, a 1536x1024 painting), draws it at 960x640 in Chromium
// (/opt/pw-browsers) and encodes WebP, stepping the quality down from 0.62 to 0.45 until the WebP
// file is at most 150 KB (A9; the integrator measured q 0.6 at about 141 KB). It writes
// `export default 'data:image/webp;base64,...'` plus ATLAS_PLACEHOLDER = false and ATLAS_SIZE.
// The data URL is a third bigger than the WebP; the build's A8 size rule counts that.
//
//   node tools/make-atlas.mjs                       # writes src/ui/assets/atlas-image.js
//   node tools/make-atlas.mjs --out=/tmp/x/atlas.js # somewhere else (a dry run)
//   node tools/make-atlas.mjs --map=<file.html>     # another copy of the illustrated map
//
// Playwright is not a project dependency: it comes from the global npm root (NODE_PATH).
// Owner: WP8.
import { execSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { Buffer } from 'node:buffer';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const args = Object.fromEntries(process.argv.slice(2).map(a => { const [k, v] = a.replace(/^--/, '').split('='); return [k, v ?? true]; }));
const mapFile = path.resolve(args.map || path.join(root, '..', 'aethermoor-interactive-image-map-polished.html'));
const outFile = path.resolve(args.out || path.join(root, 'src/ui/assets/atlas-image.js'));
const W = 960, H = 640, LIMIT = 150 * 1024;
const QUALITIES = [0.62, 0.6, 0.58, 0.56, 0.54, 0.52, 0.5, 0.48, 0.46, 0.45];

if (!existsSync(mapFile)) { console.error(`make-atlas: ${mapFile} not found`); process.exit(1); }
const html = readFileSync(mapFile, 'utf8');
const m = html.match(/__AETHERMOOR_EMBEDDED_MAP_ART\s*=\s*"(data:image\/png;base64,[A-Za-z0-9+/=]+)"/);
if (!m) { console.error('make-atlas: no embedded PNG (window.__AETHERMOOR_EMBEDDED_MAP_ART) in the map file'); process.exit(1); }
const png = m[1];
console.log(`make-atlas: embedded PNG ${(png.length / 1024).toFixed(0)} KB of base64`);

const require = createRequire(import.meta.url);
let pw;
try { pw = require('playwright'); } catch { pw = require(path.join(process.env.NODE_PATH || execSync('npm root -g').toString().trim(), 'playwright')); }
const exe = ['/opt/pw-browsers/chromium'].find(p => existsSync(p));
const browser = await pw.chromium.launch(exe ? { executablePath: exe } : {});
let result;
try {
  const page = await browser.newPage();
  result = await page.evaluate(async ({ src, W, H, LIMIT, QUALITIES }) => {
    const img = new Image();
    img.src = src;
    await img.decode();
    const c = document.createElement('canvas');
    c.width = W; c.height = H;
    const g = c.getContext('2d');
    g.imageSmoothingEnabled = true;
    g.imageSmoothingQuality = 'high';
    g.drawImage(img, 0, 0, W, H);
    const tried = [];
    for (const q of QUALITIES) {
      const url = c.toDataURL('image/webp', q);
      if (!url.startsWith('data:image/webp')) return { error: 'this Chromium cannot encode WebP' };
      const bytes = atob(url.slice(url.indexOf(',') + 1)).length;
      tried.push({ q, bytes, len: url.length });
      if (bytes <= LIMIT) return { url, q, tried, src: { w: img.naturalWidth, h: img.naturalHeight } };
    }
    return { error: 'no quality down to 0.45 fits in the limit', tried };
  }, { src: png, W, H, LIMIT, QUALITIES });
} finally {
  await browser.close();
}
for (const t of result.tried || []) console.log(`  q ${t.q.toFixed(2)}: ${(t.bytes / 1024).toFixed(1)} KB WebP (${(t.len / 1024).toFixed(1)} KB as a data URL)`);
if (result.error) { console.error(`make-atlas FAILED: ${result.error}`); process.exit(1); }

const bytes = Buffer.from(result.url.split(',')[1], 'base64').length;
const kb = n => (n / 1024).toFixed(1) + ' KB';
const src = `// The player's illustrated map, embedded (M3 spec §5.6, A9). GENERATED by tools/make-atlas.mjs; do not edit.
// Source: aethermoor-interactive-image-map-polished.html (${result.src.w}x${result.src.h} PNG), drawn at ${W}x${H}.
// WebP quality ${result.q}: ${kb(bytes)} of WebP, ${kb(result.url.length)} as this data URL (limit 150 KB).
// Markers use the illustrated map's viewBox (1200x800), the same 3:2 aspect as the image.
// Screens fall back to the procedural parchment when the image fails to load (or ATLAS_PLACEHOLDER).
// Owner: WP8.
export const ATLAS_PLACEHOLDER = false;
export const ATLAS_SIZE = Object.freeze({ w: ${W}, h: ${H} });
export default '${result.url}';
`;
mkdirSync(path.dirname(outFile), { recursive: true });
writeFileSync(outFile, src);
console.log(`make-atlas: wrote ${path.relative(process.cwd(), outFile) || outFile} (q ${result.q}, ${kb(bytes)} WebP, ${kb(result.url.length)} data URL)`);
